version: "2.0"

services:
  mongodb:
    build: ./date
    ports:
      - '27018:27017'
    volumes:
      - './date/mongo/db:/data/db'
    restart: always
  bot:
    environment:
      - BOT_MONGODB_HOST=mongodb
      - BOT_MONGODB_PORT=27018
      - 'PRODUCTION_TOKEN='
      - 'TEST_TOKEN='
    build: ./bot
    links:
      - mongodb
    volumes:
      - './bot:/opt/app'
    restart: always
